cors:
  originPatterns: "http://localhost:8080,http://localhost:3000,https://roger.com.br"
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/rest_with_spring?useTimezone=true&serverTimezone=UTC
    username: root
    password: admin
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    show-sql: false
springdoc:
  pathsToMach: "/api/**/v1/**"
  swagger-ui:
    use-root-path: true
